"""
URL configuration for pet_service project.

The `urlpatterns` list routes URLs to  For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from main.views import (
    index_page,
    login_page,
    logout_page,
    register_page,
    update_avatar,
    edit_profile,
    profile_page,
    add_pet,
    edit_pet,
    delete_pet,
    pet_profile,
    l_f_page,
    lost_page,
    found_page,
    delete_chat,
    delete_post,
    likes,
    like_post,
    net,
    create_post,
    post_detail,
    add_new_page,
    user_profile,
    follow_user,
    like_animal_pet_market,
    unlike_animal_pet_market,
    liked_animals_pet_market,
    AnimalListView,
    AnimalCreateView,
    AnimalDetailView,
    avito_page,
    VendorDashboardView_pet_market,
    EditAnimalView_pet_market,
    DeleteAnimalView_pet_market,
    report_lost_pet,
    notifications_list,
    notification_detail,
    mark_all_as_read,
    user_list,
    chat_combined,
    add_medical_record,
    add_document,
    pedigree_page,
    add_ancestor,
    edit_ancestor,
    delete_ancestor,
    download_pedigree_pdf,
    start_chat,
    send_message,
    toggle_favorite,
    FavoriteListView,
    ProductListView,
    ProductDetailView,
    checkout_view,
    update_cart_item,
    remove_cart_item,
    add_to_cart,
    cart_view,
    order_detail,
    seller_dashboard,
    product_create_view,
    edit_product,
    delete_product,
    food_page,
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index_page),
    path("accounts/login/", login_page, name="login"),
    path("login/", login_page, name="login"),
    path("logout/", logout_page, name="logout"),
    path("registration/", register_page, name="register"),
    # path('profile/', profile_page, name='profile'),
    path("update-avatar/", update_avatar, name="update_avatar"),
    path("update_avatar/", update_avatar, name="update_avatar"),
    path("profile/edit/", edit_profile, name="edit_profile"),
    path("profile/", profile_page, name="profile"),
    path("pet/add/", add_pet, name="add_pet"),
    path("pet/<int:pet_id>/edit/", edit_pet, name="edit_pet"),
    path("pet/<int:pet_id>/delete/", delete_pet, name="delete_pet"),
    path("pet/<int:pet_id>/", pet_profile, name="pet_profile"),
    path("lost_and_found/", l_f_page),
    path("lost_and_found/lost/", lost_page),
    path("lost_and_found/found/", found_page),
    path("chat/<int:chat_id>/delete/", delete_chat, name="delete_chat"),
    path("delete_post/<int:pk>/", delete_post, name="delete_post"),
    path("likes", likes, name="likes"),
    path("like_post/<int:pk>/", like_post, name="like_post"),
    path("net", net, name="net"),
    path("post/create/", create_post, name="create_post"),
    path("post/<int:pk>/", post_detail, name="post_detail"),
    path("post/<int:pk>/like/", like_post, name="like_post"),
    path("add_post/", add_new_page, name="add_post"),
    path("user/<str:username>/", user_profile, name="user_profile"),
    path("follow/<str:username>/", follow_user, name="follow_user"),
    path("like/<int:animal_id>/", like_animal_pet_market, name="like_animal_pet_market"),
    path(
        "unlike/<int:animal_id>/",
        unlike_animal_pet_market,
        name="unlike_animal_pet_market",
    ),
    path("liked-animals/", liked_animals_pet_market, name="liked_animals_pet_market"),
    path("market/", AnimalListView.as_view(), name="animal_list"),
    path("market/<int:pk>/", AnimalDetailView.as_view(), name="animal_detail"),
    path("new/", AnimalCreateView.as_view(), name="animal_create"),
    path("avito/", avito_page),
    path(
        "vendor-pets/dashboard/",
        VendorDashboardView_pet_market.as_view(),
        name="vendor_dashboard_pet_market",
    ),
    path(
        "vendor-pets/animals/<int:pk>/edit/",
        EditAnimalView_pet_market.as_view(),
        name="edit_animal_pet_market",
    ),
    path(
        "vendor-pets/animals/<int:pk>/delete/",
        DeleteAnimalView_pet_market.as_view(),
        name="delete_animal_pet_market",
    ),
    path("new/", AnimalCreateView.as_view(), name="animal_create"),
    path("report-lost-pet/", report_lost_pet, name="report_lost_pet"),
    path("notifications/", notifications_list, name="notifications_list"),
    path(
        "notifications/<int:notification_id>/",
        notification_detail,
        name="notification_detail",
    ),
    path("notifications/mark-all-read/", mark_all_as_read, name="mark_all_as_read"),
    path("lost/", lost_page),
    path("found/", found_page),
    path("add_post/", add_new_page),
    path("users/", user_list, name="user_list"),
    path("chats/", chat_combined, name="chat_combined"),  # Без chat_id
    path("chats/<int:chat_id>/", chat_combined, name="chat_detail"),  # С chat_id
    # path('pet/pedigree/<int:pet_id>', pedigree_page, name='pedigree'),
    path("pet/<int:pet_id>/medical/add/", add_medical_record, name="add_medical_record"),
    path("pet/<int:pet_id>/documents/add/", add_document, name="add_document"),
    path("pet/<int:pet_id>/pedigree/", pedigree_page, name="pedigree"),
    path("pet/<int:pet_id>/pedigree/add-ancestor/", add_ancestor, name="add_ancestor"),
    path(
        "pet/<int:pet_id>/pedigree/edit-ancestor/<int:ancestor_id>/",
        edit_ancestor,
        name="edit_ancestor",
    ),
    path(
        "pet/<int:pet_id>/pedigree/delete-ancestor/<int:ancestor_id>/",
        delete_ancestor,
        name="delete_ancestor",
    ),
    path(
        "pet/<int:pet_id>/pedigree/download-pdf/",
        download_pedigree_pdf,
        name="download_pedigree_pdf",
    ),
    # path('pet/<int:pet_id>/pedigree/', pedigree_page, name='pedigree'),
    # Остальные URL
    path("chat/start/<int:user_id>/", start_chat, name="start_chat"),
    path("chat/send/<int:chat_id>/", send_message, name="send_message"),
    path("food/", food_page, name="food"),
    # path('predigree/', predigree_page),
    # path('editing_profile_pet/', editing_profile_pet_page),
    path("favorites/toggle/<int:product_id>/", toggle_favorite, name="toggle_favorite"),
    path("favorites/", FavoriteListView.as_view(), name="favorite_list"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product_detail"),
    path("checkout/", checkout_view, name="checkout"),
    path("cart/update/<int:item_id>/", update_cart_item, name="update_cart_item"),
    path("cart/remove/<int:item_id>/", remove_cart_item, name="remove_cart_item"),
    path("cart/add/<int:product_id>/", add_to_cart, name="add_to_cart"),
    path("cart/", cart_view, name="cart_view"),
    path("order_detail/", order_detail, name="order_detail"),
    path("seller/", seller_dashboard, name="seller_dashboard"),
    path("seller/add/", product_create_view, name="add_product"),
    path("seller/edit/<int:pk>/", edit_product, name="edit_product"),
    path("seller/delete/<int:pk>/", delete_product, name="delete_product"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product_detail"),
    path("cart/", cart_view, name="cart_view"),
    path("cart/add/<int:product_id>/", add_to_cart, name="add_to_cart"),
    path("cart/update/<int:item_id>/", update_cart_item, name="update_cart_item"),
    path("cart/remove/<int:item_id>/", remove_cart_item, name="remove_cart_item"),
    path("checkout/", checkout_view, name="checkout"),
    path("favorites/", FavoriteListView.as_view(), name="favorite_list"),
    path("favorite/toggle/<int:product_id>/", toggle_favorite, name="toggle_favorite"),
    path("seller/", seller_dashboard, name="seller_dashboard"),
    path("seller/product/add/", product_create_view, name="product_create"),
    path("seller/product/edit/<int:pk>/", edit_product, name="edit_product"),
    path("seller/product/delete/<int:pk>/", delete_product, name="delete_product"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
