# Generated by Django 5.0.2 on 2025-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_post_options_remove_post_description_pet_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="bio",
            field=models.TextField(blank=True, default="", verbose_name="О питомце"),
        ),
    ]
