# Generated by Django 5.0.2 on 2025-04-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_chat_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["-updated_at"]},
        ),
    ]
