# Generated by Django 5.0.2 on 2025-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_review_product_remove_review_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pet_type",
            field=models.CharField(
                choices=[
                    ("cat", "Для кошек"),
                    ("dog", "Для собак"),
                    ("kitten", "Для котят"),
                    ("puppy", "Для щенков"),
                ],
                default="cat",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("dry", "Сухой корм"),
                    ("wet", "Влажный корм"),
                    ("premium", "Премиум"),
                    ("holistic", "Холистик"),
                    ("medicinal", "Лечебный"),
                ],
                default="dry",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="PetType",
        ),
    ]
