# Generated by Django 5.0.2 on 2025-04-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_product_pet_type_alter_product_food_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
