# Generated by Django 5.0.2 on 2025-04-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_chat_options"),
        ("main", "0011_order_orderitem"),
    ]

    operations = []
