# Generated by Django 5.0.2 on 2025-04-28 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnimalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="animal_listings/")),
            ],
        ),
        migrations.CreateModel(
            name="AnimalBreed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.animalcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_free", models.BooleanField(default=False)),
                ("age", models.PositiveIntegerField(help_text="Возраст в месяцах")),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("baby", "Детеныш (до 6 мес)"),
                            ("young", "Молодой (6 мес - 2 года)"),
                            ("adult", "Взрослый (2+ года)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(choices=[("M", "Самец"), ("F", "Самка")], max_length=1),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[("pedigree", "Породистый"), ("regular", "Обычный")],
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("main_image", models.ImageField(upload_to="animal_listings/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "additional_images",
                    models.ManyToManyField(blank=True, to="main.animalimage"),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.animalbreed",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.animalcategory",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animalimage",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="main.animallisting",
            ),
        ),
    ]
