# Generated by Django 5.0.2 on 2025-04-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_animalcategory_animalimage_animalbreed_animallisting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalbreed",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="animallisting",
            name="breed",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="animallisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("dogs", "Собаки"),
                    ("cats", "Кошки"),
                    ("birds", "Птицы"),
                    ("rodents", "Грызуны"),
                    ("reptiles", "Рептилии"),
                    ("other", "Другие"),
                ],
                max_length=20,
            ),
        ),
    ]
