# Generated by Django 5.0.2 on 2025-04-28 16:23

from django.db import migrations
from django.utils.text import slugify


# def generate_slugs(apps, schema_editor):
#     AnimalListing = apps.get_model("main", "AnimalListing")
#     for animal in AnimalListing.objects.filter(slug=""):
#         animal.slug = slugify(animal.title)
#         animal.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_animalbreed_description_alter_animallisting_breed_and_more"),
    ]

    operations = []
