# Generated by Django 5.0.2 on 2025-04-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_auto_20250428_1923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animallisting",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("baby", "Детеныш (до 6 мес)"),
                    ("young", "Молодой (6 мес - 2 года)"),
                    ("adult", "Взрослый (2+ года)"),
                ],
                max_length=10,
                verbose_name="Возрастная группа",
            ),
        ),
        migrations.DeleteModel(
            name="AnimalBreed",
        ),
        migrations.DeleteModel(
            name="AnimalCategory",
        ),
    ]
