# Generated by Django 5.0.2 on 2025-04-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_animallisting_age_group_delete_animalbreed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animallisting",
            name="breed",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Порода"),
        ),
    ]
