# Generated by Django 5.0.2 on 2025-04-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_animallisting_breed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animallisting",
            name="slug",
        ),
    ]
