# Generated by Django 5.0.2 on 2025-05-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_delete_good"),
        ("main", "0020_remove_animallisting_slug"),
    ]

    operations = []
