# Generated by Django 5.0.2 on 2025-05-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_likesmarket"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
