# Generated by Django 5.0.2 on 2025-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_message_image_alter_message_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
