# Generated by Django 5.0.2 on 2025-05-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_document_medicalrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedigree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, verbose_name="Регистрационный номер"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=100, verbose_name="Окрас"),
                ),
                (
                    "breeder",
                    models.CharField(blank=True, max_length=200, verbose_name="Заводчик"),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Подтверждена"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "pet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedigree",
                        to="main.pet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ancestor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Кличка")),
                (
                    "breed",
                    models.CharField(blank=True, max_length=100, verbose_name="Порода"),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=50, verbose_name="Регистрационный номер"),
                ),
                ("generation", models.PositiveIntegerField(verbose_name="Поколение")),
                (
                    "position",
                    models.PositiveIntegerField(verbose_name="Позиция в поколении"),
                ),
                ("is_male", models.BooleanField(default=True, verbose_name="Самец")),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "pedigree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancestors",
                        to="main.pedigree",
                    ),
                ),
            ],
            options={
                "ordering": ["generation", "position"],
                "unique_together": {("pedigree", "generation", "position")},
            },
        ),
    ]
