# Generated by Django 5.0.2 on 2025-05-11 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_profile_avatar_alter_orderitem_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LostPetReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "found_location",
                    models.TextField(verbose_name="Место, где нашли питомца"),
                ),
                (
                    "contact_info",
                    models.TextField(blank=True, verbose_name="Контактная информация"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("found", "Найден"),
                            ("returned", "Возвращен владельцу"),
                        ],
                        default="found",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lost_reports",
                        to="main.pet",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_lost_pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Найденный питомец",
                "verbose_name_plural": "Найденные питомцы",
                "ordering": ["-created_at"],
            },
        ),
    ]
