# Generated by Django 5.0.2 on 2025-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
