# Generated by Django 5.0.2 on 2025-05-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_notification_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_bestseller",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_new",
        ),
    ]
