# Generated by Django 5.0.2 on 2025-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_product_is_bestseller_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ancestor',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='ancestor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='food_type',
            field=models.CharField(choices=[('dry', 'Сухой корм'), ('wet', 'Влажный корм'), ('premium', 'Премиум'), ('holistic', 'Холистик')], default='dry', max_length=20),
        ),
    ]
